#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

do_mount_fs() {
	grep -q "$1" /proc/filesystems || return
	test -d "$2" || mkdir -p "$2"
	mount -t "$1" "$1" "$2"
}

do_mknod() {
	test -e "$1" || mknod "$1" "$2" "$3" "$4"
}

mkdir -p /proc
mount -t proc proc /proc

do_mount_fs sysfs /sys
do_mount_fs debugfs /sys/kernel/debug
do_mount_fs devtmpfs /dev
do_mount_fs devpts /dev/pts
do_mount_fs tmpfs /dev/shm

mkdir -p /run
mkdir -p /var/run

do_mknod /dev/console c 5 1
do_mknod /dev/null c 1 3
do_mknod /dev/zero c 1 5

if [ ! -d "/cache" ]; then
mkdir /cache
fi
if [ ! -d "/backup" ]; then
mkdir /backup
fi
udevd -d
udevadm trigger --action=add --subsystem-match=block
udevadm settle
boot_times
rst_flag=`/usr/bin/devmem2 0x44e00f08 | grep "Read at" | awk {'print $6'}`
let "reboot_flag=rst_flag & 0x02"
/usr/bin/devmem2 0x44e00f08 w 0x2
if [ $reboot_flag -eq 0 ];then
    /tools/adv-ota.sh 2>&1 | tee /cache/recovery/log
else
    /tools/adv-backup.sh 2>&1 | tee /backup/recovery/log
fi
exec sh </dev/console >/dev/console 2>/dev/console 
