#hostapd.VHT80.conf
ctrl_interface=/var/run/hostapd
interface=uap0
driver=nl80211
ssid=FGS060N_VHT80_SSID_5G
hw_mode=a
channel=36
beacon_int=100
dtim_period=1
wmm_enabled=1
max_num_sta=10
ieee80211n=1
rts_threshold=256
fragm_threshold=2346
auth_algs=1
send_probe_response=1
ieee80211ac=1
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=42
vht_capab=[HTC-VHT][SOUNDING-DIMENSION-2][BF-ANTENNA-4][MAX-A-MPDU-LEN-EXP7][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN][SHORT-GI-80][RXLDPC]
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][LDPC]
ieee80211d=1
country_code=US
