# Sample udhcpd configuration file (/etc/udhcpd.conf)
start 192.168.11.20
end 192.168.11.254

# The interface that udhcpd will use
interface uap0  #default: eth0
opt dns 192.168.11.2 192.168.11.10
option subnet 255.255.255.0
opt router 192.168.10.2
opt wins 192.168.10.10
option dns 129.219.13.81 # appened to above DNS servers for a total of 3
option domain local
option lease 864000 # 10 days of seconds
